### ISSUE TITLE
Checker's false-invalid as it may raise an exception: multiset.core.MultiSet cannot be cast to clojure.lang.IObj

### ISSUE THREAD

**Issue by bogdando** [aphyr/jepsen#104]
I have a custom test in my fork [0], it *almost* works well, but a false-invalid analysis due to an exception [1]

Any help with troubleshooting? It seems related to jepsen core things, not the test :/

[0] https://github.com/bogdando/jepsen/tree/rabbit_pcmk
[1] http://pastebin.com/UpPpgLKS

**Comment by bogdando** [comment]
@aphyr please take a look

**Comment by bogdando** [comment]
The patch https://github.com/aphyr/jepsen/pull/105 fixes the issue magically, now I can see the real failure reason in the analysis:

{:queue {:valid? false, :error "can't dequeue 137"},
 :total-queue
 {:valid? true,
  :lost #{},
  :recovered #{144 143 146 142 145},
  :recovered-frac 5/147,
  :unexpected-frac 0,
  :unexpected nil,
  :lost-frac 0,
  :duplicated-frac 1/147,
  :ok-frac 1,
  :duplicated #{137}},
 :valid? false}

**Comment by bogdando** [comment]
Well, the ":unexpected nil," looks a bit ugly, but at least other useful data presents with the patch...

**Comment by aphyr** [comment]
```
multiset.core.MultiSet cannot be cast to clojure.lang.IObj
 at clojure.core/with_meta (core.clj:217)  
    clojure.core$set.invoke (core.clj:3957)
    jepsen.checker$reify__6627.check (checker.clj:172)
```

You have a multiset, and the checker calls `set` on it. Multisets don't have a set representation, which is probably why this failed. Might be a checker bug around `unexpected`, but I recall the rabbit test running fine last I hacked on it. No guarantees, of course. ;-)  Might also be a mismatch between the history values and the checker.

**Comment by bogdando** [comment]
As far as I've just reused the code from the master branch as is, the bug seems vaild.

**Comment by bogdando** [comment]
I have no idea then how to fix this

**Comment by bogdando** [comment]
Should be fixed by https://github.com/aphyr/jepsen/commit/ed17b08da4019539d53cfe961b329ab2234aa79e
