### ISSUE TITLE
Is jepsen/checkouts/knossos supposed to be there?

### ISSUE THREAD

**Issue by nhahtdh** [aphyr/jepsen#116]
I find [this symbolic link](https://github.com/aphyr/jepsen/blob/master/jepsen/checkouts/knossos) in jepsen/checkouts, which points to `/home/aphyr/knossos`. I guess this can be removed without any error, right?

**Comment by aphyr** [comment]
Uh, yeah that should be fine. Forgot you can actually commit directories which are symlinks.
