### ISSUE TITLE
mongodb idempotent error conversion seems to be backwards?

### ISSUE THREAD

**Issue by kornysietsma** [aphyr/jepsen#120]
Hi - I might just be not understanding the intention, but in the macro "with-errors" in mongodb.core the following code:

      `(let [error-type# (if (~idempotent-ops (:f ~op))
                       :fail
                       :info)]

Seems to be doing the opposite of what is intended - when called with `(with-errors op #{:read}` it will turn all *read* errors into :fail, and all other errors into :info.

Apologies if I'm just not understanding the goal here.

**Comment by aphyr** [comment]
Yup, you're reading it right. That's what it's supposed to do. Reads are idempotent so we can safely assume they failed, in the event of an indeterminate response. Just an optimization to cut down on the checker state space.

**Comment by kornysietsma** [comment]
ah, I think I get it now - socket timeouts etc. are indeterminate, so go to :info not :fail as they might have succeeded.

Sorry to have wasted any of your time!

**Comment by aphyr** [comment]
Ah to be clear, socket timeouts map to *either* info or fail depending on whether the operation is idempotent or not. Every info we can treat as a fail cuts the verification complexity by a factor of 2, but it's only safe to assume an op failed if it wouldn't affect the state.
On May 16, 2016 9:08 AM, Korny Sietsma <notifications@github.com> wrote:ah, I think I get it now - socket timeouts etc. are indeterminate, so go to :info not :fail as they might have succeeded.

Sorry to have wasted any of your time!
