### ISSUE TITLE
What are pending operations in the checker/total-queue?

### ISSUE THREAD

**Issue by bogdando** [aphyr/jepsen#126]
I'm very sorry to asking questions in the issues, but could you clarify (in the docs?) what are those Pending reported in the checker, for an example report:

{:queue
 {:valid? true,
  :final-queue
  {:pending
   #{10859 ... snip ...
     8879 10860 13488 9063}}},
 :total-queue
 {:valid? false,
  :lost
  #{ ... snip ... 9063},
  :recovered #{},
  :recovered-frac 0,
  :unexpected-frac 0,
  :unexpected #{},
  :lost-frac 142/16775,
  :duplicated-frac 0,
  :ok-frac 6986/16775,
  :duplicated #{}},

The pending 10859 was only invoked to be enqueued with unknown result, in the history:
4288    :invoke :enqueue        10859
while the 9063 was enq'ed OK, then reported as lost:
285     :invoke :enqueue        9063
285     :ok     :enqueue        9063
...but it is still remaining in the pending list!

What magic stays behind this? And do you think it is doable to add a pending-frac number to report as well? And the most disturbing Q: if a test run A has pending X,  B has Y, and Y < X, does that mean the "B has a better result than A"?

**Comment by aphyr** [comment]
Pending operations, as you've observed, are those which could be pending application: invoked but neither confirmed nor denied. See any Jepsen talk for details.

**Comment by bogdando** [comment]
But the 9063 example I described was enq'ed OK, then reported as lost:
285 :invoke :enqueue 9063
285 :ok :enqueue 9063

**Comment by aphyr** [comment]
Ah, now that I'm back at a computer and can look at the source, it looks like you're running two different checkers with different semantics. :queue's :final-queue is the final model state from a conservative evaluation of the known-successful ops. :pending is a field of that queue's model. https://github.com/aphyr/jepsen/blob/master/jepsen/src/jepsen/checker.clj#L84
