### ISSUE TITLE
jepsen tests failed, not #39?

### ISSUE THREAD

**Issue by garyxia** [aphyr/jepsen#127]
Every test failed  like this: I have ssh StrictHostKeyChecking no in ~/ssh/config. There is no known_hosts file. 

The system is Debian Jessie 8.4. Installing openjdk 1.8 is not straightforward as it is still in testing. 

I think this is similar to issue #39 but not the same. It looks like java jna conflict of sort. 
This happens 100% time and for all tests. Here is the output for zookeeper test. 

Please help me!

gary@debian-jepsen1:~/jepsen/zookeeper$ lein test
INFO  org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.0-1202560, built on 11/16/2011 07:18 GMT
INFO  org.apache.zookeeper.ZooKeeper - Client environment:host.name=debian-jepsen1
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_91
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/home/gary/jepsen/zookeeper/test:/home/gary/jepsen/zookeeper/src:/home/gary/jepsen/zookeeper/dev-resources:/home/gary/jepsen/zookeeper/resources:/home/gary/jepsen/zookeeper/target/classes:/home/gary/.m2/repository/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/gary/.m2/repository/org/clojure/math.combinatorics/0.1.1/math.combinatorics-0.1.1.jar:/home/gary/.m2/repository/org/apache/zookeeper/zookeeper/3.4.0/zookeeper-3.4.0.jar:/home/gary/.m2/repository/org/clojure/algo.generic/0.1.2/algo.generic-0.1.2.jar:/home/gary/.m2/repository/org/jboss/netty/netty/3.2.2.Final/netty-3.2.2.Final.jar:/home/gary/.m2/repository/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:/home/gary/.m2/repository/interval-metrics/interval-metrics/1.0.0/interval-metrics-1.0.0.jar:/home/gary/.m2/repository/knossos/knossos/0.2.4/knossos-0.2.4.jar:/home/gary/.m2/repository/clj-ssh/clj-ssh/0.5.11/clj-ssh-0.5.11.jar:/home/gary/.m2/repository/com/jcraft/jsch.agentproxy.jsch/0.0.7/jsch.agentproxy.jsch-0.0.7.jar:/home/gary/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar:/home/gary/.m2/repository/jepsen/jepsen/0.0.9/jepsen-0.0.9.jar:/home/gary/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar:/home/gary/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar:/home/gary/.m2/repository/com/jcraft/jsch.agentproxy.sshagent/0.0.7/jsch.agentproxy.sshagent-0.0.7.jar:/home/gary/.m2/repository/zookeeper-clj/zookeeper-clj/0.9.3/zookeeper-clj-0.9.3.jar:/home/gary/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar:/home/gary/.m2/repository/com/jcraft/jsch.agentproxy.pageant/0.0.7/jsch.agentproxy.pageant-0.0.7.jar:/home/gary/.m2/repository/commons-codec/commons-codec/1.7/commons-codec-1.7.jar:/home/gary/.m2/repository/clj-tuple/clj-tuple/0.1.2/clj-tuple-0.1.2.jar:/home/gary/.m2/repository/com/jcraft/jsch.agentproxy.usocket-nc/0.0.7/jsch.agentproxy.usocket-nc-0.0.7.jar:/home/gary/.m2/repository/com/jcraft/jsch.agentproxy.core/0.0.7/jsch.agentproxy.core-0.0.7.jar:/home/gary/.m2/repository/com/boundary/high-scale-lib/1.0.6/high-scale-lib-1.0.6.jar:/home/gary/.m2/repository/org/clojars/pallix/analemma/1.0.0/analemma-1.0.0.jar:/home/gary/.m2/repository/clj-time/clj-time/0.6.0/clj-time-0.6.0.jar:/home/gary/.m2/repository/hiccup/hiccup/1.0.5/hiccup-1.0.5.jar:/home/gary/.m2/repository/org/clojure/tools.logging/0.2.6/tools.logging-0.2.6.jar:/home/gary/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar:/home/gary/.m2/repository/potemkin/potemkin/0.3.4/potemkin-0.3.4.jar:/home/gary/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar:/home/gary/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar:/home/gary/.m2/repository/com/jcraft/jsch/0.1.51/jsch-0.1.51.jar:/home/gary/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/gary/.m2/repository/byte-streams/byte-streams/0.1.4/byte-streams-0.1.4.jar:/home/gary/.m2/repository/org/fressian/fressian/0.6.3/fressian-0.6.3.jar:/home/gary/.m2/repository/com/jcraft/jsch.agentproxy.usocket-jna/0.0.7/jsch.agentproxy.usocket-jna-0.0.7.jar:/home/gary/.m2/repository/gnuplot/gnuplot/0.1.1/gnuplot-0.1.1.jar:/home/gary/.m2/repository/org/clojars/achim/multiset/0.1.0/multiset-0.1.0.jar:/home/gary/.m2/repository/org/clojure/data.fressian/0.2.0/data.fressian-0.2.0.jar:/home/gary/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/home/gary/.m2/repository/avout/avout/0.5.4/avout-0.5.4.jar:/home/gary/.m2/repository/riddley/riddley/0.1.6/riddley-0.1.6.jar
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
INFO  org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
INFO  org.apache.zookeeper.ZooKeeper - Client environment:os.version=3.16.0-4-amd64
INFO  org.apache.zookeeper.ZooKeeper - Client environment:user.name=gary
INFO  org.apache.zookeeper.ZooKeeper - Client environment:user.home=/home/gary
INFO  org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/home/gary/jepsen/zookeeper

lein test jepsen.zookeeper-test

lein test :only jepsen.zookeeper-test/zk-test

ERROR in (zk-test) (FutureTask.java:122)
expected: (:valid? (:results (jepsen/run! (zk/zk-test "3.4.5+dfsg-2"))))
  actual: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
 at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    java.util.concurrent.FutureTask.get (FutureTask.java:192)
    clojure.core$deref_future.invoke (core.clj:2186)
    clojure.core$future_call$reify__6736.deref (core.clj:6683)
    clojure.core$deref.invoke (core.clj:2206)
    clojure.core$map$fn__4553.invoke (core.clj:2622)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.RT.seq (RT.java:507)
    clojure.core/seq (core.clj:137)
    clojure.core$dorun.invoke (core.clj:3009)
    clojure.core$doall.invoke (core.clj:3025)
    jepsen.core$run_BANG_$fn__6833.invoke (core.clj:398)
    jepsen.core$run_BANG_.invoke (core.clj:379)
    jepsen.zookeeper_test/fn (zookeeper_test.clj:7)
    clojure.test$test_var$fn__7670.invoke (test.clj:704)
    clojure.test$test_var.invoke (test.clj:704)
    clojure.test$test_vars$fn__7692$fn__7697.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars$fn__7692.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars.invoke (test.clj:718)
    clojure.test$test_all_vars.invoke (test.clj:728)
    clojure.test$test_ns.invoke (test.clj:747)
    clojure.core$map$fn__4553.invoke (core.clj:2624)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1735)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invoke (core.clj:632)
    clojure.test$run_tests.doInvoke (test.clj:762)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:630)
    user$eval85$fn__144$fn__175.invoke (form-init802407220195414458.clj:1)
    user$eval85$fn__144$fn__145.invoke (form-init802407220195414458.clj:1)
    user$eval85$fn__144.invoke (form-init802407220195414458.clj:1)
    user$eval85.invoke (form-init802407220195414458.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6782)
    clojure.lang.Compiler.eval (Compiler.java:6772)
    clojure.lang.Compiler.load (Compiler.java:7227)
    clojure.lang.Compiler.loadFile (Compiler.java:7165)
    clojure.main$load_script.invoke (main.clj:275)
    clojure.main$init_opt.invoke (main.clj:280)
    clojure.main$initialize.invoke (main.clj:308)
    clojure.main$null_opt.invoke (main.clj:343)
    clojure.main$main.doInvoke (main.clj:421)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
 at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open (JNAUSocketFactory.java:114)
    com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open (SSHAgentConnector.java:80)
    com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init> (SSHAgentConnector.java:48)
    clj_ssh.agent$sock_agent_connector.invoke (agent.clj:15)
    clj_ssh.agent$connect.invoke (agent.clj:35)
    clj_ssh.ssh$ssh_agent.invoke (ssh.clj:148)
    jepsen.control$session.invoke (control.clj:193)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:630)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1868)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:634)
    clojure.core$bound_fn_STAR_$fn__4439.doInvoke (core.clj:1890)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:630)
    jepsen.core$fcatch$wrapper__6696.doInvoke (core.clj:55)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$pmap$fn__6744$fn__6745.invoke (core.clj:6729)
    clojure.core$binding_conveyor_fn$fn__4444.invoke (core.clj:1916)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)

Ran 1 tests containing 1 assertions.
0 failures, 1 errors.
Tests failed.
gary@debian-jepsen1:~/jepsen/zookeeper$

**Comment by nhahtdh** [comment]
Do you have `libjna-java` installed?

**Comment by garyxia** [comment]
Yes I do. From the env print out at the beginning of the traces you can see I have /home/gary/.m2/repository/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar. I used openjdk 1.8 as instructed by the README.md. I switched to Oracle Java 8 and resolved this issue. I don't know java. It looks to me like openjdk is still in testing phase and it sounds similar to Windows's dll of hell!
