### ISSUE TITLE
Broken link in https://github.com/aphyr/jepsen/blob/master/doc/db.md

### ISSUE THREAD

**Issue by alf239** [aphyr/jepsen#132]
Quoting https://github.com/aphyr/jepsen/blob/master/doc/db.md,

> noop-test, like all Jepsen tests, is a map with keys like :os, :name, :db, etc. See jepsen.core for an overview of test structure, and jepsen.core/run for the full definition of a test.

The `jepsen.core` here is a link to https://github.com/aphyr/jepsen/blob/master/doc/jepsen/src/jepsen/core.clj which is no longer there. Should it be https://github.com/aphyr/jepsen/blob/master/jepsen/src/jepsen/core.clj instead?

**Comment by aphyr** [comment]
Yep
