### ISSUE TITLE
consider using core.logic or wiring in z3 SMT solver for analysis

### ISSUE THREAD

**Issue by johanatan** [aphyr/jepsen#154]
Hi,

Have you considered replacing your custom analysis logic with a core.logic implementation or wiring the professional-grade z3 SMT solver in? Do you think either of these options would offer any advantage over the current custom implementation?

**Comment by aphyr** [comment]
I have a research project using constraint programming for serializability analysis; it it works well, I may port that work back to Knossos. My guess is that core.logic is not going to outperform Knossos, but you're welcome to give it a shot. :)
