### ISSUE TITLE
Push new version to Clojars?

### ISSUE THREAD

**Issue by AeroNotix** [aphyr/jepsen#28]
0.0.3-SNAPSHOT in Clojars is from The Great Before, it seems.

**Comment by jhalterman** [comment]
0.0.6 is out now so this sucker can probably be closed.

**Comment by bogdando** [comment]
Galera test is referring to the 0.0.7:

Could not find artifact jepsen:jepsen:jar:0.0.7-SNAPSHOT in clojars (https://clojars.org/repo/)

So this issue, looks still a valid
