### ISSUE TITLE
Add couchbase to the test suite

### ISSUE THREAD

**Issue by schrepfler** [aphyr/jepsen#41]
I've found https://github.com/mbsimonovic/jepsen-couchbase (blog post http://milansimonovic.com/2014/07/22/smashing-couchbase/)  which tries to replicate the testing on couchbase but that effort got stuck a bit. Can you build on that or try to help Milan?

**Comment by Yaneeve** [comment]
Would also like to read of your experiences of putting couchbase to the Jepsen test

**Comment by chester89** [comment]
Yep, me too

**Comment by colinrgodsey** [comment]
likewise

**Comment by alnewkirk** [comment]
I'm also extremely interested in this.

**Comment by ryanmaclean** [comment]
I'll chime in with a +1, only a year later :) 
CB 4 is just around the corner, might be worth another look.

**Comment by patrickpilch** [comment]
+1
Very interested

**Comment by JeanFrancoisContour** [comment]
+1 for me too.

**Comment by yelhouti** [comment]
+1 for me two :)
