### ISSUE TITLE
User-provided SSH info is ignored

### ISSUE THREAD

**Issue by jhalterman** [aphyr/jepsen#60]
Caveat: I'm not too experienced with clojure, but..

It looks like jepsen is using [pmap created](https://github.com/aphyr/jepsen/blob/master/jepsen/src/jepsen/core.clj#L60) threads to create SSH sessions using dynamic variables to house the connection information, which isn't working since the dynamic variable values are set in a different thread than the SSH connection attempt takes place in. The result is basically that user-supplied username, password, etc., are ignored, and the defaults are always used.

**Comment by jkni** [comment]
I can't reproduce this - are you still seeing this? I'd be happy to help.

**Comment by jhalterman** [comment]
I am still seeing this. One quick way to verify is to log the username [here](https://github.com/aphyr/jepsen/blob/master/jepsen/src/jepsen/control.clj#L187).  Then you can run something like the aerospike tests, adding some ssh info [here](https://github.com/aphyr/jepsen/blob/master/aerospike/src/aerospike/core.clj#L421):

```
:ssh     {:username "foo"
             :password "foo"}
```

**Comment by jkni** [comment]
Strange - that's exactly how I verified from latest master.

I get the failed connection attempts I'd expect to see since the username/password combo doesn't exist, and the credentials logged at the site you mentioned are "foo"/"foo".

I'll think about this and hopefully come up with something soon.

**Comment by jhalterman** [comment]
Not knowing clojure too well I'm going out on a limb, but this could be a bit of non-deterministic behavior caused by mixing threads with dynamic vars? At any rate, it does look like the vars are set in one thread and read from another, which should be problematic.

**Comment by aphyr** [comment]
Futures should preserve dynamic bindings, but we might need to add an explicit bound-fn somewhere.

**Comment by jhalterman** [comment]
bound-fn* on the jepsen.core/with-resources start call seems to do it
