### ISSUE TITLE
Error removing systemd

### ISSUE THREAD

**Issue by jhalterman** [aphyr/jepsen#61]
When running jepsen for the first time on a set of machines, I hit an error in the debian os setup which causes jepsen to fail when attempting to remove systemd:

```
systemd is the active init system, please switch to another before removing systemd.
dpkg: error processing package systemd (--purge):
 subprocess installed pre-removal script returned error exit status 1
Failed to stop lib-init-rw.mount: Unit lib-init-rw.mount not loaded.
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The [debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764186) describing this issue mentions that the machine needs to be rebooted after sysvinit is installed before systemd can be uninstalled. Manually rebooting my machines solves the problem, and I'm not sure if there's a nice way for Jepsen to handle this, but just something to consider.

**Comment by stapelberg** [comment]
I ran into this, too. I wonder why jepsen requires sysvinit at all…?

**Comment by jhalterman** [comment]
Not sure why sysvinit is needed, but lately I've been using the [jepsen docker](https://github.com/aphyr/jepsen/tree/master/docker) setup, which works great and installs sysvinit during the container creation so that Jepsen doesn't have to later on.

**Comment by aphyr** [comment]
Jepsen needs sysvinit because most of the systems we test don't work under systemd.

**Comment by stapelberg** [comment]
Which ones did you try that did not work under systemd? I’m having a hard time believing that popular systems don’t work with an init system as present in major distributions as systemd. I only tried running jepsen’s etcd test, and etcd works fine under systemd, so forcing sysvinit seems unnecessary for my specific use-case at least :).

**Comment by aphyr** [comment]
Last I tried, ZK, aerospike, mongo, elasticsearch, ...

**Comment by nhahtdh** [comment]
What sort of problem did you run into with systemd? The thing is, Debian and Ubuntu switches over to systemd, which limits the choice of OS version when testing chronos.

**Comment by aphyr** [comment]
A bunch of Debian packages and databases don't work with systemd so I stopped trying.

**Comment by nhahtdh** [comment]
I managed to run the chronos test by installing both sysvinit and systemd on Debian Jessie. I haven't checked whether the code works for a clean system, though.
