### ISSUE TITLE
Error running etcd test

### ISSUE THREAD

**Issue by jimonreal** [aphyr/jepsen#67]
I'm having the following error running the etcd test using the docker option,

$ lein with-profile etcd test :only jepsen.system.etcd-test/register-test

WARN ignoring checkouts directory knossos as it does not contain a project.clj file.

lein test jepsen.system.etcd-test

lein test :only jepsen.system.etcd-test/register-test

ERROR in (register-test) (AFn.java:429)
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ArityException: Wrong number of args (1) passed to: generator/delay
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.AFn.invoke (AFn.java:32)
    jepsen.system.etcd_test/fn (etcd_test.clj:31)
    clojure.test$test_var$fn__7187.invoke (test.clj:704)
    clojure.test$test_var.invoke (test.clj:704)
    clojure.test$test_vars$fn__7209$fn__7214.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars$fn__7209.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars.invoke (test.clj:718)
    clojure.test$test_all_vars.invoke (test.clj:728)
    clojure.test$test_ns.invoke (test.clj:747)
    clojure.core$map$fn__4245.invoke (core.clj:2559)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1654)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invoke (core.clj:626)
    clojure.test$run_tests.doInvoke (test.clj:762)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:624)
    user$eval85$fn__200$fn__251.invoke (form-init4707164460779162580.clj:1)
    user$eval85$fn__200$fn__201.invoke (form-init4707164460779162580.clj:1)
    user$eval85$fn__200.invoke (form-init4707164460779162580.clj:1)
    user$eval85.invoke (form-init4707164460779162580.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6693)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.Compiler.loadFile (Compiler.java:7086)
    clojure.main$load_script.invoke (main.clj:274)
    clojure.main$init_opt.invoke (main.clj:279)
    clojure.main$initialize.invoke (main.clj:307)
    clojure.main$null_opt.invoke (main.clj:342)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

Ran 1 tests containing 1 assertions.
0 failures, 1 errors.
Tests failed.
Error encountered performing task 'test' with profile(s): 'etcd'
Tests failed

What am I doing wrong?

**Comment by aphyr** [comment]
Probably want to check out an older version of jepsen; the etcd tests are from before it was a library.
On Jul 2, 2015 7:02 AM, José Monreal <notifications@github.com> wrote:I'm having the following error running the etcd test using the docker option,

$ lein with-profile etcd test :only jepsen.system.etcd-test/register-test

WARN ignoring checkouts directory knossos as it does not contain a project.clj file.

lein test jepsen.system.etcd-test

lein test :only jepsen.system.etcd-test/register-test

ERROR in (register-test) (AFn.java:429)
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ArityException: Wrong number of args (1) passed to: generator/delay
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.AFn.invoke (AFn.java:32)
    jepsen.system.etcd_test/fn (etcd_test.clj:31)
    clojure.test$test_var$fn__7187.invoke (test.clj:704)
    clojure.test$test_var.invoke (test.clj:704)
    clojure.test$test_vars$fn__7209$fn__7214.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars$fn__7209.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars.invoke (test.clj:718)
    clojure.test$test_all_vars.invoke (test.clj:728)
    clojure.test$test_ns.invoke (test.clj:747)
    clojure.core$map$fn__4245.invoke (core.clj:2559)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1654)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invoke (core.clj:626)
    clojure.test$run_tests.doInvoke (test.clj:762)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:624)
    user$eval85$fn__200$fn__251.invoke (form-init4707164460779162580.clj:1)
    user$eval85$fn__200$fn__201.invoke (form-init4707164460779162580.clj:1)
    user$eval85$fn__200.invoke (form-init4707164460779162580.clj:1)
    user$eval85.invoke (form-init4707164460779162580.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6693)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.Compiler.loadFile (Compiler.java:7086)
    clojure.main$load_script.invoke (main.clj:274)
    clojure.main$init_opt.invoke (main.clj:279)
    clojure.main$initialize.invoke (main.clj:307)
    clojure.main$null_opt.invoke (main.clj:342)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

Ran 1 tests containing 1 assertions.
0 failures, 1 errors.
Tests failed.
Error encountered performing task 'test' with profile(s): 'etcd'
Tests failed

**Comment by jimonreal** [comment]
I did checkout older versions like:

d9a53ca957f20b67fe1a58814a31ffd4c0f6c868 (from before 2015-12-31)
82832b126fa7c4498b63cb63777a3bb79d370972 (from before 2014-06-09)

But with those I get the following error:

# lein with-profile etcd test :only jepsen.system.etcd-test/register-test
Could not transfer artifact com.boundary:high-scale-lib:pom:1.0.3 from/to boundary-site (http://maven.boundary.com/artifactory/repo): Failed to transfer file: http://maven.boundary.com/artifactory/repo/com/boundary/high-scale-lib/1.0.3/high-scale-lib-1.0.3.pom. Return code is: 500 , ReasonPhrase:Server Error.
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Tests failed.
Error encountered performing task 'test' with profile(s): 'etcd'
Tests failed.


I grep the whole directory to find where was this dependency, but I could not find it. The only version for high-scale-lib is 1.0.6, I do not know where the 1.0.3 is comming from.

Any clue on this?

**Comment by aphyr** [comment]
Ah, yeah, Boundary took down their repo. You can bump the version to .12 IIRC
On Jul 2, 2015 8:28 AM, José Monreal <notifications@github.com> wrote:I did checkout older versions like:

d9a53ca (from before 2015-12-31)
82832b1 (from before 2014-06-09)

But with those I get the following error:

lein with-profile etcd test :only jepsen.system.etcd-test/register-test

Could not transfer artifact com.boundary:high-scale-lib:pom:1.0.3 from/to boundary-site (http://maven.boundary.com/artifactory/repo): Failed to transfer file: http://maven.boundary.com/artifactory/repo/com/boundary/high-scale-lib/1.0.3/high-scale-lib-1.0.3.pom. Return code is: 500 , ReasonPhrase:Server Error.
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Tests failed.
Error encountered performing task 'test' with profile(s): 'etcd'
Tests failed.

I grep the whole directory to find where was this dependency, but I could not find it. The only version for high-scale-lib is 1.0.6, I do not know where the 1.0.3 is comming from.

Any clue on this?

**Comment by jimonreal** [comment]
Thank you for your time Asphyr. Regarding to your answer, what do you mean by "You can bump the version to .12 IIRC", and how can do I do that?

**Comment by aphyr** [comment]
Sorry, was on my phone. You can bump the high-scale-lib dependency to 1.0.12, which I pushed to Knossos a bit ago. The Knossos API changes might invalidate that though... https://github.com/aphyr/jepsen/commit/ca13ab30e6467b271736dc62a11042aced45431b

**Comment by jimonreal** [comment]
That's fine. I could not find where in the code was the version dependency, because I the version in the code is 1.0.6 but the error says 1.0.3, can you please give me a hint here?

**Comment by aphyr** [comment]
It's a transitive dependency through knossos; `lein deps :tree` will show it. Sorry bout this; Boundary took their maven repo offline and didn't upload that version of the jar to maven central, so all the old builds are gonna fail. :(

**Comment by jimonreal** [comment]
Wow. That kinda sucks. So I should update the knossos version to use to 1.0.12? but still use the old code to test etcd and consul with jepsen, right?

**Comment by aphyr** [comment]
No, you want knossos 0.2.2--see the commit I linked, which fixes this same issue for HEAD. That might not be API-compatible with the etcd tests (they're fairly old at this point) so you might have to :exclude high-scale-lib from the knossos dep and add 1.0.12 to project.clj directly.

**Comment by jimonreal** [comment]
Ok, thank you once again Aphyr

**Comment by jimonreal** [comment]
But this high-scale-lib where should I get it if its no longer in boundary?

**Comment by aphyr** [comment]
Version 1.0.12 is on maven central; they just didn't push the older versions.

**Comment by jimonreal** [comment]
Warning: specified :main without including it in :aot. 
Implicit AOT of :main will be removed in Leiningen 3.0.0. 
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.
Could not find artifact com.boundary:high-scale-lib:jar:1.0.12 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.boundary:high-scale-lib:jar:1.0.12 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.


could be that the repo is other?

**Comment by aphyr** [comment]
Err, 1.0.6, sorry.

**Comment by jimonreal** [comment]
Ok, now it installs, but when running the test again I get the same result:

lein with-profile etcd test :only jepsen.system.etcd-test/register-test
WARN ignoring checkouts directory knossos as it does not contain a project.clj file.

lein test jepsen.system.etcd-test

lein test :only jepsen.system.etcd-test/register-test

ERROR in (register-test) (AFn.java:429)
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ArityException: Wrong number of args (1) passed to: generator/delay
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.AFn.invoke (AFn.java:32)
...


I am using the branch at master

**Comment by aphyr** [comment]
Yeah, jepsen's probably diverged too far from when these tests ran. Gonna take more work to resurrect them; sorry. :(

**Comment by aphyr** [comment]
Wait, you're running master? Think we're going in circles here. You need to be running a checkout from last year; master's no longer compatible with these tests.

**Comment by jimonreal** [comment]
Oh! sorry, I guessed I misunderstood you. So I will checkout from August last year, any day I make this changes, right?

**Comment by aphyr** [comment]
Yeah, you'll need to make that change to project.clj on top of whatever version you check out.

**Comment by jimonreal** [comment]
lein test :only jepsen.system.etcd-test
Could not find artifact clojurewerkz:elastisch:jar:2.0.0-beta5-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact verschlimmbesserung:verschlimmbesserung:jar:0.1.1-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Tests failed.

Are this ones also in knossos?

**Comment by aphyr** [comment]
Naw, that's in project.clj. Sorry man, I wish I had time to bring this test back to life for ya but I've got a lot of other stuff on my plate right now. May be more trouble than its worth if you don't know Clojure. :(

**Comment by jimonreal** [comment]
I'll try to bring it back to life. No worries.
I found the lines, let me see if I can continue by my own now.
Thank you

**Comment by jimonreal** [comment]
Im getting an Auth failure,

lein test :only jepsen.system.etcd-test/register-test

ERROR in (register-test) (Session.java:512)
Uncaught exception, not in assertion.
expected: nil
  actual: com.jcraft.jsch.JSchException: Auth fail
 at com.jcraft.jsch.Session.connect (Session.java:512)
    com.jcraft.jsch.Session.connect (Session.java:183)
    clj_ssh.ssh$connect.invoke (ssh.clj:327)
    jepsen.control$session.invoke (control.clj:177)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:624)
    jepsen.core$fcatch$wrapper__6797.doInvoke (core.clj:39)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$pmap$fn__6328$fn__6329.invoke (core.clj:6463)
    clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)

Ran 1 tests containing 1 assertions.
0 failures, 1 errors.
Tests failed.
Error encountered performing task 'test' with profile(s): 'etcd'
Tests failed.


By the way Im using the Docker implementation.

**Comment by jimonreal** [comment]
I think its from the jepsen/src/jepsen/control.clj

**Comment by jimonreal** [comment]
the jepsen.core-test/ssh-test fails. How should this test work? I see some declarations at the top for username and password, but it should use root and the ssh credentiales created at the begining, right?

**Comment by aphyr** [comment]
You gotta follow the setup process for your nodes--see lxc.md for details.

**Comment by jimonreal** [comment]
Roger

**Comment by jimonreal** [comment]
I have added the config file on the host machine. And I can do an ssh to each of the nodes started at startup of this Dockerized jepsen. But when running the test, it gives me auth failure. How can I debug it?

**Comment by aphyr** [comment]
Could be an SSH agent issue? I dunno, I haven't hacked on that code in a couple years. Might be worth printing out the contents of *session* in jepsen/control.clj to see what it thinks your credentials are.

**Comment by jimonreal** [comment]
Thanks!
The username used is "ubuntu". At the top of the control.clj I see the following:

; STATE STATE STATE STATE
(def ^:dynamic *host*     "Current hostname"              nil)
(def ^:dynamic *session*  "Current clj-ssh session"       nil)
(def ^:dynamic *trace*    "Shall we trace commands?"      false)
(def ^:dynamic *dir*      "Working directory"             "/")
(def ^:dynamic *sudo*     "User to sudo to"               nil)
(def ^:dynamic *username* "Username"                      "ubuntu")
(def ^:dynamic *password* "Password (for login and sudo)" "ubuntu")
(def ^:dynamic *private-key-path*         "SSH identity file"     nil)
(def ^:dynamic *strict-host-key-checking* "Verify SSH host keys"  :yes)


Could this be the problem?

**Comment by jimonreal** [comment]
it Worked! i had to set the path for the public key and user root :)

**Comment by jimonreal** [comment]
aphyr, the nodes array with(n1,...n5) where is it created?

**Comment by aphyr** [comment]
jepsen.tests/noop-test IIRC?
