### ISSUE TITLE
Hazelcast and Coherence

### ISSUE THREAD

**Issue by sathomps** [aphyr/jepsen#88]
I would love to see these added to the suite of tests.  If no one grabs them, I'll work on them when I have a chance.

Thanks

**Comment by quanah** [comment]
+1 for hazelcast.  I'd love to see a callmemaybe on it too ;)

**Comment by ittaiz** [comment]
+1 as well for hazelcast

**Comment by ittaiz** [comment]
@aphyr May I ask why it was closed?

**Comment by aphyr** [comment]
Mostly because of my own anger and guilt over never being able to satisfy a volume of support requests which vastly exceeds my ability to do unpaid work for strangers.
On May 24, 2016 12:51 AM, Ittai Zeidman <notifications@github.com> wrote:@aphyr May I ask why it was closed?

**Comment by ittaiz** [comment]
ok. fair enough.

**Comment by aphyr** [comment]
Done. https://jepsen.io/analyses/hazelcast-3-8-3
