### ISSUE TITLE
Make it easier to run with LXC, with better docs and possibly bundled scripts

### ISSUE THREAD

**Issue by hausdorff** [aphyr/jepsen#96]
I'm an LXC noob and I was looking over the instructions in `lxc.md` and found them to be quite mysterious. I was just wondering if you were receptive to improvements on the docs and/or scripts that will just run everything out of the box.

**Comment by aphyr** [comment]
Sure, go for it! Those are my notes from each time I go through the setup process, but I haven't managed to generalize em well. Also LXC is a fast-moving target!

There's a vagrant script out there somewhere too, and I think an AMI maybe? I need to put work into those as official things.
